export const Permissions = {
  // Platform
  CREATE_TENANT: "CREATE_CHAIN",
  ARCHIVE_TENANT: "ARCHIVE_CHAIN",
  VIEW_SUPER_ADMIN: "VIEW_PLATFORM_DASHBOARD",

  // Chain
  MANAGE_CHAIN: "MANAGE_CHAIN",
  CREATE_RESTAURANT: "CREATE_RESTAURANT",

  // Orders
  ADVANCE_ORDER: "ADVANCE_ORDER_STATUS",
  CREATE_ORDER: "CREATE_ORDER",

  // Staff
  MANAGE_STAFF: "MANAGE_STAFF",

  // Menu
  MANAGE_MENU: "MANAGE_MENU",

  // Tables
  MANAGE_TABLES: "MANAGE_TABLES",

  // Seed
  RUN_SEED: "RUN_SEED",
} as const;
